### ISSUE TITLE
Need bouton magique ! 

### ISSUE THREAD

**Issue by RochDLY** [samszo/DWM_18-19#15]
Besoin d'un bouton magique pour créer un sunburst séquencé dans mon trombinoscope !
https://bl.ocks.org/kerryrodden/7090426

**Comment by samszo** [comment]
1. faire fonctionner l'exemple en local
2. faire fonctionner avec données persos
3. adapter le design à l'emplacement dans le trombino

**Comment by samszo** [comment]
pour t'aider : 
implémentation de l'exemple : http://jardindesconnaissances.univ-paris8.fr/public/planning/formation
- le code de définition des référence pour le graph : https://github.com/samszo/jardindesconnaissances/blob/master/application/controllers/PlanningController.php#L184
- le code de la page cf. https://github.com/samszo/jardindesconnaissances/blob/master/application/views/scripts/planning/formation.phtml
