### ISSUE TITLE
pourquoi les boucles ne marche pas avec spip

### ISSUE THREAD

**Issue by zahir0699** [samszo/DWM_18-19#16]
http://www.samszo.univ-paris8.fr/DWM/18-19/etudiants/zahir/ecrire/

**Comment by samszo** [comment]
parce que tu ne sais pas les faire

**Comment by samszo** [comment]
c'est ici http://www.samszo.univ-paris8.fr/DWM/18-19/etudiants/zahir/ecrire/?exec=skeleditor&f=..%2Fsquelettes%2Farticle.html
???

**Comment by zahir0699** [comment]
oui
