### ISSUE TITLE
spip: problème recalculer page

### ISSUE THREAD

**Issue by HakimP8** [samszo/DWM_18-19#17]
je ne parviens pas à recalculer la page.
Je n'arrive pas à situer le problème. 
Voila ce qui s'affiche:
![capture d ecran 2018-11-19 a 12 52 08](https://user-images.githubusercontent.com/43647952/48947444-7dee3800-ef31-11e8-8d80-8dc73ea7af4d.png)

http://www.samszo.univ-paris8.fr/DWM/18-19/etudiants/hakim/

**Comment by samszo** [comment]
le plus simple est d'ajouter à la fin de l'url : ?var_mode=recalcul
