### ISSUE TITLE
mise a jour du squelette dans le local spip

### ISSUE THREAD

**Issue by natachabile** [samszo/DWM_18-19#23]
Bonjour Monsieur,

pourriez-vous mettre mon squellette a jour dans le local spip, j'aimerais avoir tout pareil comme sur le serveur dans mon local spip pour le modifier directement en local avant de le charger sur le serveur.

j'ai essayé de recopier tout page par page mais j'ai un soucis au niveau de la licence.txt:
![licence](https://user-images.githubusercontent.com/43675060/49233545-885b7680-f3f6-11e8-9746-439d86442532.PNG)

ps: n'oubliez pas de me donner les droits de modification svp.
merci

**Comment by samszo** [comment]
où sont les fichiers ?
où est la base de données ?

**Comment by natachabile** [comment]
les liens:
- sur le serveur: http://www.samszo.univ-paris8.fr/DWM/18-19/etudiants/natacha/ecrire/?exec=skeleditor
-en local: C:\wamp64\www\spip\squelettes
