### ISSUE TITLE
Erreur importation JSON

### ISSUE THREAD

**Issue by RochDLY** [samszo/DWM_18-19#27]
Je n'ai pas d'erreur dans les outils de dev mais je n'ai pas de donnée dans les variables.:

https://github.com/samszo/DWM_18-19/blob/0452464b18d641688f5211d54551841657eee275/RochDLY/sonar/application/public.html#L54

**Comment by samszo** [comment]
Attention $getJSON est une méthode asynchrone !
cf. https://api.jquery.com/jquery.getjson/
Les données sont récupérées dans la fonction callback
Regardes mes modifications où j'utilise d3.json cf. https://github.com/d3/d3-fetch#json
plus besoin de jquery

**Comment by RochDLY** [comment]
![github](https://user-images.githubusercontent.com/43650596/53176708-f034ee00-35ee-11e9-8006-8f65cc57e842.PNG)
C'est bon ! Les données sont présentes ! Je n'ai plus qu'à terminer la répartition sur les cercles ;)
Merci !
