### ISSUE TITLE
Question SPIP

### ISSUE THREAD

**Issue by GDiouck** [samszo/DWM_18-19#5]
Comment afficher le logo des articles
Comment peut-on changer l’image bouclée sur les articles
Quelle action peut-on mettre pour stocker les données à travers le formulaire de contact

**Comment by samszo** [comment]
mettre #LOGO_ARTICLE à l'emplacement souhaité
cf. https://github.com/samszo/DWM_18-19/blob/master/GDiouck/squelettes/article.html#L20
