### ISSUE TITLE
Comment puis-je modifier un template sur spip sur l'url "http://www.samszo.univ-paris8.fr/DWM/18-19/etudiants/yhilderal/" ?

### ISSUE THREAD

**Issue by yohanhask** [samszo/DWM_18-19#7]
Bonjour, 

J'ai eu un problème avec mon premier template (dans l'édition de squelette dans mon espace privé), j'y ai supprimé des dossiers qui concernait le css et j'aimerai le remplacer totalement.

Je peux supprimer les fichiers mais je ne peux pas supprimer les dossiers "assets" et "images".

lien : https://prnt.sc/lm1ohs

**Comment by samszo** [comment]
OK mettre dans GitHub un répertoire squelette avec la version à transférer sur le serveur
